spring.config.import=optional:file:.env[.properties]
app.db.seed=false

security.jwt.secret-key=${SECURITY_JWT_SECRET_KEY}
security.jwt.expiration-time=${SECURITY_JWT_EXPIRATION_TIME}
security.jwt.refresh.expiration-time=${SECURITY_JWT_REFRESH_EXPIRATION_TIME}

spring.security.oauth2.client.registration.google.client-id=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SCOPE}

spring.security.oauth2.client.registration.google.client-name=Google

logging.level.org.springframework.security=NONE
logging.level.liquibase=NONE

springdoc.swagger-ui.oauth.client-id=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}
springdoc.swagger-ui.oauth.client-secret=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}
springdoc.swagger-ui.oauth.scopes=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SCOPE}

springdoc.swagger-ui.oauth.use-pkce=true
springdoc.swagger-ui.oauth.redirect-url=http://localhost:8080/swagger-ui/oauth2-redirect.html
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false

springdoc.swagger-ui.with-credentials=false

frontend.url=${FRONTEND_URL}

app.protocol.storage=${APP_PROTOCOL_STORAGE}
app.cookie.secure=${APP_COOKIE_SECURE}
